# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_processing_system7_0_0/Diagram_7_Segment_Display_processing_system7_0_0.xci
# IP: The module: 'Diagram_7_Segment_Display_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_processing_system7_0_0/Diagram_7_Segment_Display_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Diagram_7_Segment_Display_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_processing_system7_0_0/Diagram_7_Segment_Display_processing_system7_0_0.xci
# IP: The module: 'Diagram_7_Segment_Display_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_processing_system7_0_0/Diagram_7_Segment_Display_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Diagram_7_Segment_Display_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
