# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/Diagram_7_Segment_Display_system_ila_0_0.xci
# IP: The module: 'Diagram_7_Segment_Display_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/bd_6bb8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6bb8 || ORIG_REF_NAME==bd_6bb8} -quiet] -quiet

# IP: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/ip/ip_0/bd_6bb8_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6bb8_ila_lib_0 || ORIG_REF_NAME==bd_6bb8_ila_lib_0} -quiet] -quiet

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/Diagram_7_Segment_Display_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Diagram_7_Segment_Display_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6bb8_ila_lib_0 || ORIG_REF_NAME==bd_6bb8_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6bb8_ila_lib_0 || ORIG_REF_NAME==bd_6bb8_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/ip/ip_0/bd_6bb8_ila_lib_0_ooc.xdc

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/bd_6bb8_ooc.xdc

# IP: D:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/Diagram_7_Segment_Display_system_ila_0_0.xci
# IP: The module: 'Diagram_7_Segment_Display_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/bd_6bb8.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6bb8 || ORIG_REF_NAME==bd_6bb8} -quiet] -quiet

# IP: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/ip/ip_0/bd_6bb8_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_6bb8_ila_lib_0 || ORIG_REF_NAME==bd_6bb8_ila_lib_0} -quiet] -quiet

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/Diagram_7_Segment_Display_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Diagram_7_Segment_Display_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6bb8_ila_lib_0 || ORIG_REF_NAME==bd_6bb8_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_6bb8_ila_lib_0 || ORIG_REF_NAME==bd_6bb8_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/ip/ip_0/bd_6bb8_ila_lib_0_ooc.xdc

# XDC: d:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/7_Segment_Display.srcs/sources_1/bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_system_ila_0_0/bd_0/bd_6bb8_ooc.xdc
