webtalk_init -webtalk_dir C:/Users/schumae/Desktop/EE365/Lab4/Vivado_Encoder_Lab4.sim/sim_1/behav/xsim/xsim.dir/all_design_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 13 16:01:44 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "175495545_1777507777_210710067_627" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "aff5777b-9a9e-4eb8-ac1d-569b4eefccb6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "75026cbd556f44439f2d2cc9132dd5bc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "23" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3312 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "800 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7080_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1707250397 -regid "175495545_1777507777_210710067_627" -xml C:/Users/schumae/Desktop/EE365/Lab4/Vivado_Encoder_Lab4.sim/sim_1/behav/xsim/xsim.dir/all_design_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/schumae/Desktop/EE365/Lab4/Vivado_Encoder_Lab4.sim/sim_1/behav/xsim/xsim.dir/all_design_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/schumae/Desktop/EE365/Lab4/Vivado_Encoder_Lab4.sim/sim_1/behav/xsim/xsim.dir/all_design_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
