@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Nov 05 16:50:56 -0400 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Segment_Display_tb_behav -key {Behavioral:sim_1:Functional:Segment_Display_tb} -tclbatch Segment_Display_tb.tcl -protoinst "protoinst_files/bd_6bb8.protoinst" -protoinst "protoinst_files/bd_ab19.protoinst" -protoinst "protoinst_files/bd_6b48.protoinst" -protoinst "protoinst_files/bd_aaf9.protoinst" -protoinst "protoinst_files/bd_6bad.protoinst" -protoinst "protoinst_files/bd_ab0c.protoinst" -protoinst "protoinst_files/bd_6b5d.protoinst" -protoinst "protoinst_files/bd_aaec.protoinst" -protoinst "protoinst_files/design_tb.protoinst" -log simulate.log"
call xsim  Segment_Display_tb_behav -key {Behavioral:sim_1:Functional:Segment_Display_tb} -tclbatch Segment_Display_tb.tcl -protoinst "protoinst_files/bd_6bb8.protoinst" -protoinst "protoinst_files/bd_ab19.protoinst" -protoinst "protoinst_files/bd_6b48.protoinst" -protoinst "protoinst_files/bd_aaf9.protoinst" -protoinst "protoinst_files/bd_6bad.protoinst" -protoinst "protoinst_files/bd_ab0c.protoinst" -protoinst "protoinst_files/bd_6b5d.protoinst" -protoinst "protoinst_files/bd_aaec.protoinst" -protoinst "protoinst_files/design_tb.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
