--Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
----------------------------------------------------------------------------------
--Tool Version: Vivado v.2019.1 (win64) Build 2552052 Fri May 24 14:49:42 MDT 2019
--Date        : Tue Nov  8 23:53:05 2022
--Host        : ALIENWARE running 64-bit major release  (build 9200)
--Command     : generate_target top_level.bd
--Design      : top_level
--Purpose     : IP block netlist
----------------------------------------------------------------------------------
