# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/.Xil/Vivado-17604-ALIENWARE/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg225-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ipshared/8c62/hdl {
      d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_aw_atc.v
      d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_b_atc.v
      d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_w_atc.v
      d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_atc.v
      d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ipshared/8fd3/hdl/verilog/processing_system7_v5_5_trace_buffer.v
      d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0_1/hdl/verilog/processing_system7_v5_5_processing_system7.v
      d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0_1/synth/design_1_processing_system7_0_0.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/LUT.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/SPI_master.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/TTL_SPI_user_logic.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/TTL_serial.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/TTL_user_logic.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/btn_debounce_toggle.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/clk_enabler.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/reset_delay.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/univ_bin_counter.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5.vhd
      d:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/ip/design_1_lab5_0_0_1/synth/design_1_lab5_0_0.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/synth/design_1.vhd
      D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/lab5_fresh.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top design_1_wrapper
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/.Xil/Vivado-17604-ALIENWARE/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
