# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TE0726.xdc

# Block Designs: bd/FINAL_DIAGRAM/FINAL_DIAGRAM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM || ORIG_REF_NAME==FINAL_DIAGRAM} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_processing_system7_0_0/FINAL_DIAGRAM_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_processing_system7_0_0 || ORIG_REF_NAME==FINAL_DIAGRAM_processing_system7_0_0} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_Counter_Loader_0_0/FINAL_DIAGRAM_Counter_Loader_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_Counter_Loader_0_0 || ORIG_REF_NAME==FINAL_DIAGRAM_Counter_Loader_0_0} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_TTL_Serial_user_logic_0_0/FINAL_DIAGRAM_TTL_Serial_user_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_TTL_Serial_user_logic_0_0 || ORIG_REF_NAME==FINAL_DIAGRAM_TTL_Serial_user_logic_0_0} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_btn_debounce_toggle_0_0/FINAL_DIAGRAM_btn_debounce_toggle_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_btn_debounce_toggle_0_0 || ORIG_REF_NAME==FINAL_DIAGRAM_btn_debounce_toggle_0_0} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_btn_debounce_toggle_1_0/FINAL_DIAGRAM_btn_debounce_toggle_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_btn_debounce_toggle_1_0 || ORIG_REF_NAME==FINAL_DIAGRAM_btn_debounce_toggle_1_0} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_btn_debounce_toggle_2_0/FINAL_DIAGRAM_btn_debounce_toggle_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_btn_debounce_toggle_2_0 || ORIG_REF_NAME==FINAL_DIAGRAM_btn_debounce_toggle_2_0} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_out_LTU_0_0/FINAL_DIAGRAM_out_LTU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_out_LTU_0_0 || ORIG_REF_NAME==FINAL_DIAGRAM_out_LTU_0_0} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_univ_bin_counter_0_0/FINAL_DIAGRAM_univ_bin_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_univ_bin_counter_0_0 || ORIG_REF_NAME==FINAL_DIAGRAM_univ_bin_counter_0_0} -quiet] -quiet

# IP: bd/FINAL_DIAGRAM/ip/FINAL_DIAGRAM_Reset_Delay_0_0/FINAL_DIAGRAM_Reset_Delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FINAL_DIAGRAM_Reset_Delay_0_0 || ORIG_REF_NAME==FINAL_DIAGRAM_Reset_Delay_0_0} -quiet] -quiet

# XDC: bd/FINAL_DIAGRAM/FINAL_DIAGRAM_ooc.xdc
