# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/schumae/Desktop/EE365/Lab4/TE0726.xdc

# Block Designs: bd/Vivado_encoder_Lab4/Vivado_encoder_Lab4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Vivado_encoder_Lab4 || ORIG_REF_NAME==Vivado_encoder_Lab4} -quiet] -quiet

# IP: bd/Vivado_encoder_Lab4/ip/Vivado_encoder_Lab4_processing_system7_0_0/Vivado_encoder_Lab4_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Vivado_encoder_Lab4_processing_system7_0_0 || ORIG_REF_NAME==Vivado_encoder_Lab4_processing_system7_0_0} -quiet] -quiet

# IP: bd/Vivado_encoder_Lab4/ip/Vivado_encoder_Lab4_topLevel_0_1/Vivado_encoder_Lab4_topLevel_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Vivado_encoder_Lab4_topLevel_0_1 || ORIG_REF_NAME==Vivado_encoder_Lab4_topLevel_0_1} -quiet] -quiet

# XDC: bd/Vivado_encoder_Lab4/ip/Vivado_encoder_Lab4_processing_system7_0_0/Vivado_encoder_Lab4_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Vivado_encoder_Lab4_processing_system7_0_0 || ORIG_REF_NAME==Vivado_encoder_Lab4_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Vivado_encoder_Lab4/Vivado_encoder_Lab4_ooc.xdc
