# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/TE0726.xdc

# Block Designs: bd/Lab_5/Lab_5.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_5 || ORIG_REF_NAME==Lab_5} -quiet] -quiet

# IP: bd/Lab_5/ip/Lab_5_top_level_0_0/Lab_5_top_level_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_5_top_level_0_0 || ORIG_REF_NAME==Lab_5_top_level_0_0} -quiet] -quiet

# IP: bd/Lab_5/ip/Lab_5_processing_system7_0_0/Lab_5_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Lab_5_processing_system7_0_0 || ORIG_REF_NAME==Lab_5_processing_system7_0_0} -quiet] -quiet

# XDC: bd/Lab_5/Lab_5_ooc.xdc
