@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Nov 14 14:31:41 -0500 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 121e9139d4874ad996190e20d7f7f85b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L xilinx_vip -L secureip --snapshot design_1_wrapper_func_synth xil_defaultlib.design_1_wrapper -log elaborate.log"
call xelab  -wto 121e9139d4874ad996190e20d7f7f85b --incr --debug typical --relax --mt 2 -L xil_defaultlib -L xilinx_vip -L secureip --snapshot design_1_wrapper_func_synth xil_defaultlib.design_1_wrapper -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
