# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/My_DevOps/Fall_2022/EE365/EE365_Labs/lab5_fresh/TE0726.xdc

# XDC: new/Debug_constraints.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0_1/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_lab5_0_0_1/design_1_lab5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_lab5_0_0 || ORIG_REF_NAME==design_1_lab5_0_0} -quiet] -quiet

# XDC: bd/design_1/ip/design_1_processing_system7_0_0_1/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
