# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/My_DevOps/Fall_2022/EE365/EE365_Labs/Lab5/TE0726.xdc

# Block Designs: bd/Diagram_7_Segment_Display/Diagram_7_Segment_Display.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display || ORIG_REF_NAME==Diagram_7_Segment_Display} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_processing_system7_0_0/Diagram_7_Segment_Display_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_processing_system7_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_processing_system7_0_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_Pos_Edge_Detector_0_0/Diagram_7_Segment_Display_Pos_Edge_Detector_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_Pos_Edge_Detector_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_Pos_Edge_Detector_0_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_btn_debounce_toggle_0_0/Diagram_7_Segment_Display_btn_debounce_toggle_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_btn_debounce_toggle_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_btn_debounce_toggle_0_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_btn_debounce_toggle_1_0/Diagram_7_Segment_Display_btn_debounce_toggle_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_btn_debounce_toggle_1_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_btn_debounce_toggle_1_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_btn_debounce_toggle_2_0/Diagram_7_Segment_Display_btn_debounce_toggle_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_btn_debounce_toggle_2_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_btn_debounce_toggle_2_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_univ_bin_counter_0_0/Diagram_7_Segment_Display_univ_bin_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_univ_bin_counter_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_univ_bin_counter_0_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_out_LTU_0_0/Diagram_7_Segment_Display_out_LTU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_out_LTU_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_out_LTU_0_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_count_loader_0_0/Diagram_7_Segment_Display_count_loader_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_count_loader_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_count_loader_0_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_Reset_Delay_0_0/Diagram_7_Segment_Display_Reset_Delay_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_Reset_Delay_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_Reset_Delay_0_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_clk_enabler_0_0/Diagram_7_Segment_Display_clk_enabler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_clk_enabler_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_clk_enabler_0_0} -quiet] -quiet

# IP: bd/Diagram_7_Segment_Display/ip/Diagram_7_Segment_Display_OR_2_0_0/Diagram_7_Segment_Display_OR_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Diagram_7_Segment_Display_OR_2_0_0 || ORIG_REF_NAME==Diagram_7_Segment_Display_OR_2_0_0} -quiet] -quiet

# XDC: bd/Diagram_7_Segment_Display/Diagram_7_Segment_Display_ooc.xdc
